name: Generate Distro Snake GIF

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  generate:
    runs-on: ubuntu-latest
    name: Generate Distro Snake GIF
    steps:
      - uses: actions/checkout@v3
      - name: Generate GIF
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: dist/github-contribution-grid-snake.svg
      - name: Commit and push if changed
        run: |
          git add dist/github-contribution-grid-snake.svg
          git diff --quiet && git diff --staged --quiet || (git commit -m "Updated snake animation" && git push)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
